### ISSUE TITLE
Unescapting elements

### ISSUE THREAD

**Issue by m1guelpf** [jbaysolutions/vue2-bootstrap-table#1]
Hi!
I am trying to pass some html button as the content of the field, but the table shows the HTML instead of the button.
How can I disable this?

**Comment by syshex** [comment]
Hi. On the next release there is a render function functionality that will allow this. It is already implemented, just not released and documented yeat. Tomorrow I'll take care of it and will let you know

**Comment by syshex** [comment]
Hi there. Released 1.1.3 .  Check out the README that has an example of a renderfunction configuration etc , and give it a try.
Let me know if you find any problems with it.
