### ISSUE TITLE
Dynamic Page Size

### ISSUE THREAD

**Issue by mrlinnth** [jbaysolutions/vue2-bootstrap-table#11]
Is it possible to bind pageSize with a dropdown?
I have tried to update it using watch and computed options.
Only the pager got update correctly but the rows do not get update.

**Comment by syshex** [comment]
this is a good idea. 
marking as enhancement. 
will look into it when other fixes are done

**Comment by syshex** [comment]
got this done. 
will test thoroughly today and will release tomorrow

**Comment by syshex** [comment]
done, closing
