### ISSUE TITLE
Setting Sort Order

### ISSUE THREAD

**Issue by fwarren** [jbaysolutions/vue2-bootstrap-table#14]
How can you set a default sort order?
For example, by default sort on the 2nd column.

And how can you programmaticly set the sort order? 
Push a button and sort on Column1 and Column 3.

**Comment by syshex** [comment]
At this moment, you can't.

Will take a look at this after I fix some of the other issues. 

If you would like to give it a look and submit a PR , feel free

**Comment by syshex** [comment]
fixed
