### ISSUE TITLE
Project dead?

### ISSUE THREAD

**Issue by phires** [jbaysolutions/vue2-bootstrap-table#15]
If have some of the issues already listed here (e.g. #8 ), but it seems as if the project is dead?
Of is there still someone working on these issues?

**Comment by syshex** [comment]
Hi dapaxx. It is not dead, but at the moment we got massive amounts of projects going on and can really spare much time. I am aware of the issues being reported and am taking note. I hope for work to slow down closer to the summer, at which point we'll have more time to go through all of this and fix it up.

This is also an opensource project, so feel free to contribute with PRs .

**Comment by stevenjeff** [comment]
don't die

**Comment by syshex** [comment]
not dead
