### ISSUE TITLE
The introductory part is rather confusing

### ISSUE THREAD

**Issue by LihengGong** [jbaysolutions/vue2-bootstrap-table#18]
I spent one hour but still cannot integrate this library to my Vue project.

1. Where is this props supposed to go in the source code?
I tried multiple places but no one works
```javascript
props: {
....
}
```

2. This line does not work at all
```javascript
 VueBootstrapTable: VueBootstrapTable
```

3. There are multiple format errors.
 - Trailing commas
 - Mixed use of double quotes and single quotes

**Comment by syshex** [comment]
1- the props go here: 

```
    <vue-bootstrap-table
            :columns="columns"
            :values="values"
            :show-filter="true"
            :show-column-picker="true"
            :sortable="true"
            :paginated="true"
            :multi-column-sortable=true
            :filter-case-sensitive=false

    >
    </vue-bootstrap-table>
```

>   This line does not work at all

Why ? Can you provide mode details?  Have you imported the JS file in you HTML ?  Can you provide fiddle example of what you are doing ?     Blanket statements like "it doesn't work" without providing examples or more details are ignored.

> There are multiple format errors.

Show me .
