### ISSUE TITLE
Filter specific column

### ISSUE THREAD

**Issue by aceits** [jbaysolutions/vue2-bootstrap-table#19]
Can you add a feature that allows filtering one or more columns?
Or could it be that you have implemented it and i'm the one who missed it in the documentation?

**Comment by syshex** [comment]
Can you explain a bit more? The filter at this moment works on all columns. 
- What you are saying is make it work on just specific columns ?   
- Adding like a right-click on column header with filter and allow to define different filter for each column?

**Comment by aceits** [comment]
i want to ask you if you could add an additional configuration props maybe like : 
filterSpecificColumn: {
  type: String,
  required: false,
  default: null,
}

Your second bulletpoint might be helpful for the user, but i dont need that right now.

Thanks for keeping this project alive by the way :smile:

**Comment by aceits** [comment]
or maybe a better one:

Add this in the Configuration Props:
filterSpecificColumn: {
type: Boolean,
required: false,
default: false,
}

and in the column array definition add one more config:
filterable: Boolean

**Comment by syshex** [comment]
Ok ok ! I get it. 
So, basically , define the filter to work only on specific columns, and not others. 

I think that maybe the filterSpecificColumn  prop is not required. 
Maybe for each column have the  filterable config, by default as not required and with default =  true.

That way, out of the box, the filter is on for all columns, just as it is right now, and if you want, you can just set the  config of the column to false, and that would make it not filterable. 

How does this sound? Did I understood correctly ?

**Comment by aceits** [comment]
Yeah, briliant! That's what i want and how it should be implemented. Good job, man!
Have fun implementing it!

**Comment by syshex** [comment]
I can do it quite easily I think, was just giving it a look and should be alright. 

Do you want to give it a go? Trying to make it and submitting PR ? Should be easy enough if you want to give it a go and contribute to a opensource project. 

Let me know

**Comment by aceits** [comment]
It would take time for me to understand your codes (im still new in JS & Vue btw). I think it will be better if you do it yourself, i'll just learn from your git commit

**Comment by syshex** [comment]
Done.

[Check new Column definition](https://github.com/jbaysolutions/vue2-bootstrap-table#column-array-definition)

If you find any other problems, reopen ticket
