### ISSUE TITLE
Listener for RowClick?

### ISSUE THREAD

**Issue by Cookizza** [jbaysolutions/vue2-bootstrap-table#2]
In an older bootstrap-table npm package it was possible to listen for a click on a row. This was useful for table items with single functions, much cleaner than appending a single button to the row.

Something like:

`:onRowClick="rowClick"`

Could this be added in?

**Comment by syshex** [comment]
I'll give it a look.

**Comment by syshex** [comment]
I've done this. Would you be willing to give it a test run, or you require a release?

**Comment by Cookizza** [comment]
I can test for sure!

**Comment by syshex** [comment]
Wicked. Give me a sec to document this and push

**Comment by syshex** [comment]
Ok, done.
Javascript files at : [dist](https://github.com/jbaysolutions/vue2-bootstrap-table/tree/master/dist)

Documentation [HERE](https://github.com/jbaysolutions/vue2-bootstrap-table#row-click-handler)

Any feedback you have, let me know

**Comment by Cookizza** [comment]
Can confirm all is behaving as expected!

Awesome!

**Comment by syshex** [comment]
Sweet. Tomorrow will do the same to the Vue1 version and will make a release. If you need it sooner let me know and I'll try and get it done tonight

**Comment by Cookizza** [comment]
All good from me. I'm maybe 12 hours into a 350 hour project so I'm sure by the time we get to UAT the release will be out.

Thanks for such a great component mate, and of course the lightning fast addition here today.

Love your work!

**Comment by syshex** [comment]
No problem! Afterwards, if it is a public project let us know, so we add it to the list of projects using it.

Thanks for the feedback!

**Comment by syshex** [comment]
Released 1.1.5
