### ISSUE TITLE
Buttons in row

### ISSUE THREAD

**Issue by hanGtz92** [jbaysolutions/vue2-bootstrap-table#21]
I can not assing a customized button for each row

**Comment by syshex** [comment]
why? show us code.

**Comment by syshex** [comment]
11 day old, no comment, no code.
closing

**Comment by hanGtz92** [comment]
Sorry, I could find the code I was needing
Whit this

            {title: "Nombre", name: "nombre", renderfunction: yourCustomizedCode},

**Comment by syshex** [comment]
what is not working ?
