### ISSUE TITLE
Load values through axios get ajax request and populate table

### ISSUE THREAD

**Issue by delete-this-account** [jbaysolutions/vue2-bootstrap-table#23]

**Comment by syshex** [comment]
Hi. 
Can you show us the configuration you are using for the tables ? 
Also, using the chrome developer tools, can you see the requests being performed by the component ?

**Comment by samimi-it** [comment]
The ajax object is empty and disabled no matter what config was set.

Full example code including the php pasted below to test with the same setup.

`
"<?php  
  /*
    File path/name = ./ajax/ajaxUsers.php
  */
    
  $host = "localhost";  // Host name
  $user = "root";       // User
  $password = "root123";   // Password
  $dbname = "test";    // Database name

  // Create connection
  $con = mysqli_connect($host, $user, $password,$dbname);

  // Check connection
  if (!$con) {
      die("Connection failed: " . mysqli_connect_error());
  }

  $usersData = mysqli_query($con,"select id,name,email from users");

  $response = array();

  while($row = mysqli_fetch_assoc($usersData)){

      $response[] = $row;
  }

  echo json_encode($response);
  //exit;
  
?>"`

`"
<!doctype html>
<html lang="en">
	<head>
    <meta charset="utf-8">
		<title>vue-bootstrap-table - Fetch records from MySQL example</title>
    <link rel="stylesheet" href="css/bootstrap.min.css">
	</head>
	<body>
		<div id='app'>
     
      <div>
        <h1>Test with vue-bootstrap-table not working</h1>
        <div class="row">
        <div class="col-sm-12">
            <button @click="addItem" class="btn btn-primary"><i class="glyphicon glyphicon-plus-sign"></i> Add an item</button>
            <button @click="toggleFilter" class="btn btn-default">Toggle Filter</button>
            <button @click="togglePicker" class="btn btn-default">Toggle Column Picker</button>
            <button @click="togglePagination" class="btn btn-default">Toggle Pagination</button>
        </div>
        <br/><br/>
        
          <vue-bootstrap-table
                  :columns="columns"
                  :values="users"
                  :show-filter="showFilter"
                  :show-column-picker="showPicker"
                  :paginated="paginated"
          >
          </vue-bootstrap-table>
        </div>
      </div>
      
      <hr />
      
      <div>
        <h1>Test only with axios is working</h1>
        
        <input type='button' @click='getAxiosUsers()' value='Get All Users with axios'>
        <br><br>

        
        <table border='1' width='80%' style='border-collapse: collapse;'>
          <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Email</th>
          </tr>

          <tr v-for='user in axiosUsers'>
            <td>{{ user.id }}</td>
            <td>{{ user.name }}</td>
            <td>{{ user.email }}</td>
          </tr>
        </table>
        </div>
      
    </div>

    <script src="https://cdn.jsdelivr.net/npm/vue@2.5.21/dist/vue.js"></script>
    <script src="./vue-bootstrap-table/vue-bootstrap-table2.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.18.0/axios.js"></script>

    
    <script> 
      Vue.config.debug = true;
      Vue.config.devtools = true;

      var app = new Vue({
              el: '#app',
              mounted() {
                  console.log('Mounted!');
              },
              components: {
                VueBootstrapTable: VueBootstrapTable        
              },

              data: {
                axiosUsers: [],
                logging: [],
                showFilter: true,
                showPicker: true,
                paginated: true,
                columns: [
                    {
                        title:"ID",
                        visible: true,
                        editable: false,
                    },
                    {
                        title:"Name",
                        visible: true,
                        editable: true,
                    },
                    {
                        title:"Email",
                        visible: true,
                        editable: true,
                    }
                ],

              users: [
                  /* Test data working */
                  // {
                      // "ID": 1,
                      // "Name": "John",
                      // "Email": "john@example.com",
                  // },
                  // {
                      // "ID": 2,
                      // "Name": "Jane",
                      // "Email": "jane@example.com",
                  // },
                  // {
                      // "ID": 3,
                      // "Name": "Allen",
                      // "Email": "allen@example.com",
                  // }
                ]
              },
              methods: {
              
                  /* Test only with axios is working*/
                  getAxiosUsers: function(){
                    
                    axios.get('./ajax/ajaxUsers.php')
                    .then(function (response) {
                        app.axiosUsers = response.data;
                    })
                    .catch(function (error) {
                        console.log(error);
                    });
                  },
                  /* Test add data working */
                  addItem: function() {
                      var self = this;
                      var item = {
                          "ID" : this.users.length + 1,
                          "Name": "Test" + (this.users.length+1),
                          "Email": "test"+(this.users.length+1)+"@example.com"
                      };
                      this.users.push(item);
                  },
                  toggleFilter: function() {
                      this.showFilter = !this.showFilter;
                  },
                  togglePicker: function() {
                      this.showPicker = !this.showPicker;
                  },
                  togglePagination: function () {
                      this.paginated = !this.paginated;
                  }
              },

              events: {
                cellDataModifiedEvent: function( originalValue, newValue, columnTitle, entry) {
                  this.logging.push("Original Value : " + originalValue +
                               " | New Value : " + newValue +
                               " | Column : " + columnTitle +
                               " | Complete Entry : " +  entry );
                  },
              },
              ajax: {
                enabled: true,
                delegate: false,
                axiosConfig: {
                    /* Not working */
                    // axios({
                      // method:'get',
                      // url:'./ajax/ajaxUsers.php'
                      // })
                     // .then(function (response) {
                         // console.log(response);
                         // this.values = response.data;
                     // })
                     // .catch(function (error) {
                         // console.log(error);
                     // });
                     
                  }
              }, 
      });  
    </script>
	</body>
</html>"`

**Comment by syshex** [comment]
OK , you got this:
  
    <vue-bootstrap-table
              :columns="columns"
              :values="users"
              :show-filter="showFilter"
              :show-column-picker="showPicker"
              :paginated="paginated"
      >
      </vue-bootstrap-table>

Where in this is the ajax configuration defined?  
check :  https://github.com/jbaysolutions/vue2-bootstrap-table#configuration-props

You something like: 

      <vue-bootstrap-table
              :columns="columns"
              :values="users"
              :show-filter="showFilter"
              :show-column-picker="showPicker"
              :paginated="paginated"
              :ajax="ajax"
      >
      </vue-bootstrap-table>

where the "ajax" is the object you have defined in your vue data. Which in your case is wrong, because you have it defined not in the vue data.

Does this make sense? You need to pass the ajax property something, to let the component know it should work in ajax mode.

**Comment by samimi-it** [comment]
Thank you for your respond.
Did the required as told above and now the ajax object shows under props in vuetools, but still don't get data back from ajax as it reports `values:  array[0]` 

With hard coded users it works fine if uncommented. 

Below are the component and ajax parts i used.

```
<vue-bootstrap-table
  :columns="columns" 
  :values="users"
  :show-filter="showFilter"
  :show-column-picker="showPicker"
  :paginated="paginated"                 
  :ajax="ajax"
>
</vue-bootstrap-table>
```

```
ajax: {
  type: Object,
  required: false,
  default: function (response) {
      return {
          enabled: true,
          url: "./ajax/ajaxUsers.php",
          method: "GET",
          delegate: false,
          users: response.data,
          axiosConfig: {},
      }
  }
},
```
Full code for data below.

```
data: {
   
    /* vue table settings */
    showFilter: true,
    showPicker: true,
    paginated: true,
    columns: [
    {
        title:"ID",
        visible: true,
        editable: false,
    },
    {
        title:"Name",
        visible: true,
        editable: true,
    },
    {
        title:"Email",
        visible: true,
        editable: true,
    }
    ],
    users: [
      // {
          // "ID": 1,
          // "Name": "John",
          // "Email": "john@example.com",
      // },
      // {
          // "ID": 2,
          // "Name": "Jane",
          // "Email": "jane@test.com",
      // },
    ],
    ajax: {

      type: Object,
      required: false,
      default: function (response) {
          return {
              enabled: true,
              url: "./ajax/ajaxUsers.php",
              method: "GET",
              delegate: false,
              users: response.data,
              axiosConfig: {},

          }

      }
    },
  },
```

**Comment by syshex** [comment]
Use this ajax: 

        ajax: {
              enabled: true,
              url: "./ajax/ajaxUsers.php",
              method: "GET",
              delegate: false,
              users: response.data,
              axiosConfig: {},
          }

**Comment by syshex** [comment]
It should be working. 

Can you check if the request is being performed correctly on the network tab of your chorme development console? I want to see what it is outputting.

**Comment by syshex** [comment]
This is the documentation of the ajax expected response:

https://github.com/jbaysolutions/vue2-bootstrap-table#ajax-expected-response

**Comment by samimi-it** [comment]
Hi again and appreciated.

Below are `XHR` screen shots for `Headers`, `Params` and `Response`.

First **without filter** and second **with filter** `jane` for test which also shows that the filter is not working as response includes both records _(exiting 2 records)_ from mysql.

> **Without filter**

![clipboard-3](https://user-images.githubusercontent.com/37351787/50368155-f7ae2b80-059a-11e9-9f16-0dde4777a088.jpg)

![clipboard-7](https://user-images.githubusercontent.com/37351787/50368159-f8df5880-059a-11e9-8ea5-0d918a21da9d.jpg)

![clipboard-8](https://user-images.githubusercontent.com/37351787/50368160-f8df5880-059a-11e9-91ce-540190d20de3.jpg)

> **With filter **'jane'****

![clipboard-4](https://user-images.githubusercontent.com/37351787/50368156-f846c200-059a-11e9-87f6-7b052a80bb73.jpg)

![clipboard-5](https://user-images.githubusercontent.com/37351787/50368157-f846c200-059a-11e9-835b-fb4d28e50d8d.jpg)

![clipboard-6](https://user-images.githubusercontent.com/37351787/50368158-f846c200-059a-11e9-89ea-b7792f86838a.jpg)

**Comment by samimi-it** [comment]
Hi again.

Question: Why are these required to be set in the response from the ajax endpoint?

I was reading your documentation and noticed the `Ajax Expected Response` must contain ` echo ` and ` filtered ` as per given below.

```
Ajax Expected Response

For all requests, vue-bootstrap-table expects an object of the following type:

{
    echo: INTEGER,
    filtered: INTEGER,
    data: [OBJECT],
},

Where:

    echo : is the same integer the request provided.
    filtered : is the total amount of entries for the request, and is used for pagination
    data : is an Array of Object with the entries.

Example:

{
    echo: 1,
    filtered: 2000,
    data: [
        {
            id: 1,
            name: "Rui"
        },
        {
            id: 2,
            name: "Gustavo"
        },
    ],
},
```

**Comment by samimi-it** [comment]
Hi again and wish you happy holidays, merry Christmas and a happy new year in advance,

OK. passed the required back in the ajax response and almost getting there, but no column/data properly mapping as the rows are showing matching data count but still no data showing!

Not sure where the fields are mapped? are they php side JSON formatting issues or are there column data mapping in the component side?

This is the `ajaxUsers.php` code:

```
$usersData = mysqli_query($con,"select id,name,email from users");

$response = array();

if(isset($_GET)){
  $echo = $_GET['echo'];
  $filtered = $_GET['filter'];
}

$response['echo']     = intval($echo);
$response['filtered'] = intval($filtered);
          
while($row = mysqli_fetch_assoc($usersData)){
    $response['data'][] = $row;
}

echo json_encode($response);
exit;
```

`Ajax Response` as below:

![clipboard-13](https://user-images.githubusercontent.com/37351787/50379775-25ad7180-0668-11e9-9449-e0b9145fd454.jpg)

And `Vue Devtool Component` reports as:

![clipboard-14](https://user-images.githubusercontent.com/37351787/50379796-d4ea4880-0668-11e9-9b81-9b086a459e1a.jpg)

And `Vue Devtool Events` reports as:

![clipboard-15](https://user-images.githubusercontent.com/37351787/50379803-0f53e580-0669-11e9-8c87-1255452749bf.jpg)
