### ISSUE TITLE
Why the arrows not display

### ISSUE THREAD

**Issue by thdung002** [jbaysolutions/vue2-bootstrap-table#27]
Hi. First things thanks for your good table. It's have all function I need
But when i'm display the table doesn't see the arraow in each column header like a demo.
Could you please tell me how to fix it?
Using without any css layout
![image](https://user-images.githubusercontent.com/48899952/77324109-dfeac780-6d48-11ea-8918-76a7ea5bbb09.png)

**Comment by syshex** [comment]
Hey
Its a problem with  "Font Awesome\ 5 Free" dependency  . 

Try adding for a quick fix: 
`<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css">` .

Let me know if this fixed it for you

**Comment by thdung002** [comment]
Hey thanks for your answer
It work :D

**Comment by syshex** [comment]
Perfect ! Will give a look into this today, if I find the time.

**Comment by thdung002** [comment]
Hey some stupid question... How do I change the header column color from grey to dark?

**Comment by thdung002** [comment]
> Perfect ! Will give a look into this today, if I find the time.

Hey some stupid question....
But if I want to add a select box to filter by each column what do I need to do? Does it support or not?
