### ISSUE TITLE
Making table filter case insensitive

### ISSUE THREAD

**Issue by rubenwap** [jbaysolutions/vue2-bootstrap-table#4]
I am using the latest version (1,1,5) and I noticed that the filter search box in the table is case sensitive. I think it would be a good idea to make it case insensitive if there are no other obstacles for it. 

Thanks again for the good job with this.

**Comment by syshex** [comment]
Shouldn't be a problem. I'll look into it today!

**Comment by syshex** [comment]
Sorry for the delay. Took a few days off. 

Release 1.1.6 has this new option: 

`<vue-bootstrap-table
                    :filter-case-sensitive=false
            >`

Default is "true" , so we don't break compatibility for people using older versions.

Check it out and let me know if there is any problem

**Comment by rubenwap** [comment]
Thanks, it works totally fine as expected.
