### ISSUE TITLE
VueJS modal dialogs result in empty "<tbody>"

### ISSUE THREAD

**Issue by humblecoder** [jbaysolutions/vue2-bootstrap-table#7]
Using the example cited here [Reusable Modal Dialogs](https://adamwathan.me/2016/01/04/composing-reusable-modal-dialogs-with-vuejs/) on the same page, the vue2-bootstrap-table loses it's content on modal open and never recovers.  Looking at the page source in real-time, the header and search input remain after the modal closes, but the data simply disappears and never returns.  There is no debug information with which to trace the issue.

**Comment by humblecoder** [comment]
Update:  Per the "Vue Devtools" the table is actually losing its "value" data.  There are no known events being emitted on modal open, so I have no idea what could be triggering the change.

![screen shot 2017-08-15 at 11 00 49 pm](https://user-images.githubusercontent.com/913539/29345574-bdcb0c4c-820d-11e7-9090-cf20f2367d6e.png)
![screen shot 2017-08-15 at 11 01 04 pm](https://user-images.githubusercontent.com/913539/29345581-c85f5e24-820d-11e7-9e25-7a196f288924.png)

**Comment by syshex** [comment]
Fixed on next release 1.1.10
