### ISSUE TITLE
delegate=true dosen't render in table.

### ISSUE THREAD

**Issue by jelofsson** [jbaysolutions/vue2-bootstrap-table#8]
I'm experiencing that the data returned from the ajax request are not getting rendered in the graph when im using delegate.

**Comment by syshex** [comment]
Hi Jelofsson.  It is not dead, but at the moment we got massive amounts of projects going on and can really spare much time. I am aware of the issues being reported and am taking note. I hope for work to slow down closer to the summer, at which point we'll have more time to go through all of this and fix it up.

This is also an opensource project, so feel free to contribute with PRs .

**Comment by syshex** [comment]
Fixed on next release, which will be 1.1.10
