### ISSUE TITLE
[Vue warn]: Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "values"

### ISSUE THREAD

**Issue by paocom** [jbaysolutions/vue2-bootstrap-table#9]
I want to use ajax in vue2-bootstrap-table 
data is show but vue warn this

`[Vue warn]: Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "values"`

**Comment by syshex** [comment]
Fixed on 1.1.9
